---
title: "Anova analysis of Acropora counts per transect"
author: "Catheirne Kim"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set working directory and read in the data

Data is coral genera counts per transect. Some genera are broken up in to morphological groups such as Acropora tabulate and branching. Columns 1-5 are metadata (year, site, depth, transect 1-3 per site/depth, and num_id transects per year 1-24).

```{r read in 2015 and 2017 genera data}
library(here) # setting the working directory as a relative directory
here()

gen <- read.csv(here::here('data/genmorph.csv'))
```

## Analysis of variance (ANOVA) of tabulate Acroporas 

```{r Acropora tab per site/depth}
hist(sqrt(gen$ACRtab)) # check normality

acrt.glm <- glm(ACRtab~Year*Site*Depth, data = gen, family = "poisson")
summary(acrt.glm)

acrt.an <- aov(ACRtab~Year*Site*Depth, data = gen)
summary(acrt.an)
plot(acrt.an)
TukeyHSD(acrt.an)

library(Rmisc)
gen.acr <- summarySE(gen, "ACRtab", c("Year", "Site", "Depth"))
gen.acr
```

```{r Acropora br per site/depth}
hist(sqrt(gen$ACRbr))

acrb.lm <- lm(ACRbr~Year*Site*Depth, data = gen)
summary(acrb.lm)

acrb.an <- aov(ACRbr~Year*Site*Depth, data = gen)
summary(acrb.an)
plot(acrb.an)
TukeyHSD(acrt.an)

gen.acrbr <- summarySE(gen, "ACRbr", c("Site"))
gen.acrbr
```

