---
title: "graph-TLtemp-5m-allsites"
author: "CKim"
date: "August 4, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Rural-N ----
```{r read in Beloi 5m all data}
library(Rmisc)
library(here)
#library(tidyverse)
bel5 <- read.csv(here::here("data/rawdata/temperature/Bel5m-date-hourly.csv"))
bel5$Site <- "Rural-N"
bel5$Depth <- "5m"
head(bel5)

bel5.se <- summarySE(bel5, "Temp", c("year", "month", "Site", "Depth"))
head(bel5.se)
```
```{r read in Beloi 5m all data}
bel10 <- read.csv(here::here("data/rawdata/temperature/Bel10m-date-hourly.csv"))
bel10$Site <- "Rural-N"
bel10$Depth <- "10m"
head(bel10)

bel10.se <- summarySE(bel10, "Temp", c("year", "month", "Site", "Depth"))
head(bel10.se)
```
```{r combine 5 and 10 m }
bel.se <- rbind(bel5.se, bel10.se)

# add m.y factor
bel.se$m.y <- as.factor(paste(bel.se$month, bel.se$year, sep = "/"))
levels(bel.se$m.y)
# reodrder month/year so in chronological order
bel.se$m.y = factor(bel.se$m.y,levels(bel.se$m.y)[c(4,6,1,8,10,12,14,16,18,19,20,3,5,7,2,9,11,13,15,17)])
```

```{r plot monthly averages colored by depth}
library(ggplot2)
ggplot(bel.se, aes((m.y), (Temp), color = Depth)) + geom_point() +
   geom_smooth(method ="lm") +
   theme_classic() +
   labs(title = "Rural-N Temperature", xlab = "Month/Year", ylab = "Temperature") +
   theme(axis.text.x = element_text(angle = 90)) +
   geom_errorbar(aes(ymin = Temp-(2*se), ymax = Temp+(2*se)))
```
## difference between 5 and 10 m
```{r beloi 10-5 difference and 2se}

bel.diff <- bel10.se[,1:3]
bel.diff$delta <- bel10.se$Temp - bel5.se$Temp
bel.diff$dse <- (bel10.se$se + bel5.se$se)/2

head(bel.diff)

bel.diff$m.y <- as.factor(paste(bel.diff$month, bel.diff$year, sep = "/"))
levels(bel.diff$m.y)
bel.diff$m.y = factor(bel.diff$m.y,levels(bel.diff$m.y)[c(4,6,1,8,10,12,14,16,18,19,20,3,5,7,2,9,11,13,15,17)])

```
```{r graph beloi temp diff + 2se}
library(ggplot2)
ggplot(bel.diff, aes((m.y),(delta))) + geom_line() +
   geom_smooth(method ="lm") +
   theme_classic() +
   labs(title = "Rural-N 10-5m Temperature", xlab = "Month/Year", ylab = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90))

   
ggplot(bel.diff, aes((m.y), (delta))) + geom_point() +
   geom_smooth(method ="lm") +
   theme_classic() +
   labs(title = "Rural-N 10-5m Temperature", xlab = "Month/Year", ylab = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90)) +
   geom_errorbar(aes(ymin = delta-(2*dse), ymax = delta+(2*dse)))+
   geom_hline(yintercept = 0, color = "light blue")
```
## plot all hourly points for 5 and 10 m Beloi
```{r}
bel <- rbind(bel5, bel10)

ggplot(bel, aes(1:nrow(bel), Temp, color = Depth)) + geom_point()

ggplot(bel5, aes(1:nrow(bel5), Temp, color = Depth, alpha = 0.1 )) +
   geom_point() +
   geom_point(data =bel10, aes(1:nrow(bel10), Temp, color = Depth, alpha=0.1))
```

## Dili Rock----
```{r read in DiliRock 5m all data}
dil5 <- read.csv(here::here("data/rawdata/temperature/Dil5m-date-hourly.csv"))
dil5$Site <- "Urban-W"
dil5$Depth <- "5m"

dil5.se <- summarySE(dil5, "Temp", c("year", "month", "Site", "Depth"))

head(dil5.se)
```
```{r read in DiliRock 10m all data}
dil10 <- read.csv(here::here("data/rawdata/temperature/Dil10m-date-hourly.csv"))
dil10$Site <- "Urban-W"
dil10$Depth <- "10m"

dil10.se <- summarySE(dil10, "Temp", c("year", "month", "Site", "Depth"))

head(dil10.se)
```
```{r dilirock 10-5 difference and 2se}
dil.diff <- dil10.se[,1:3]
dil.diff$delta <- dil10.se$Temp - dil5.se$Temp
dil.diff$dse <- (dil10.se$se + dil5.se$se)/2

head(dil.diff)

dil.diff$m.y <- as.factor(paste(dil.diff$month, dil.diff$year, sep = "/"))
levels(dil.diff$m.y)
dil.diff$m.y = factor(dil.diff$m.y,levels(dil.diff$m.y)[c(4,6,1,8,10,12,14,16,18,19,20,3,5,7,2,9,11,13,15,17)])
```
```{r graph dil temp diff + 2se}
ggplot(dil.diff, aes(as.numeric(m.y), (delta)), group = 1) + geom_line() +
   geom_point() +
   theme_classic() +
   labs(title = "Urban-W 10-5m Temperature", xlab = "Month/Year", ylab = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90)) +
    geom_errorbar(aes(ymin = delta-(2*dse), ymax = delta+(2*dse))) +
   geom_hline(yintercept = 0, color = "light blue")
```
# CristoRei ----
```{r CristoRei}
cr5 <- read.csv(here::here("data/rawdata/temperature/CristoRei5m-date-hourly.csv"))
head(cr5)

cr5$Site <- "Urban-E"
cr5$Depth <- "5m"

cr5.se <- summarySE(cr5, "Temp", c("month", "year", "Site", "Depth"))
head(cr5.se)
```
```{r CristoRei 10m}
cr10 <- read.csv(here::here("data/rawdata/temperature/CristoRei10m-date-hourly.csv"))
head(cr10)

cr10$Site <- "Urban-E"
cr10$Depth <- "10m"

cr10.se <- summarySE(cr10, "Temp", c("month", "year", "Site", "Depth"))
head(cr10.se)
```
```{r graph 10-5 hourly difference and 2se}

cr.hrdiff <- cr10[3:13467,6:9]
cr.hrdiff$delta <- cr10$Temp[3:13467] - cr5$Temp[121:13585]

head(cr.hrdiff)

cr.hrdiff$m.y <- as.factor(paste(cr.hrdiff$month, cr.hrdiff$year, sep = "/"))
levels(cr.hrdiff$m.y)
cr.hrdiff$m.y = factor(cr.hrdiff$m.y,levels(cr.hrdiff$m.y)[c(4,6,1,8,10,12,14,16,18,19,20,3,5,7,2,9,11,13,15,17)])
```
```{r graph hourly cr temp diff}
ggplot(cr.hrdiff, aes(1:nrow(cr.hrdiff), (delta))) + 
   geom_point() +
   geom_smooth(method = "gam") +
   theme_classic() +
   labs(title = "Urban-E 10-5m Temperature", x = "Month/Year", y = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90)) +
       geom_hline(yintercept = 0, color = "light blue")
```

```{r cristorei 10-5 monthly difference and 2se}
cr.diff <- cr10.se[,1:3]
cr.diff$delta <- cr10.se$Temp - cr5.se$Temp
cr.diff$dse <- (cr10.se$se + cr5.se$se)/2

head(cr.diff)

cr.diff$m.y <- as.factor(paste(cr.diff$month, cr.diff$year, sep = "/"))
levels(cr.diff$m.y)
cr.diff$m.y = factor(cr.diff$m.y,levels(cr.diff$m.y)[c(4,6,1,8,10,12,14,16,18,19,20,3,5,7,2,9,11,13,15,17)])
```
```{r graph cr temp diff + 2se}
ggplot(cr.diff, aes(as.numeric(m.y), (delta)), group = 1) + geom_line() +
   geom_point() +
   theme_classic() +
   labs(title = "Urban-E 10-5m Temperature", xlab = "Month/Year", ylab = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90)) +
    geom_errorbar(aes(ymin = delta-(2*dse), ymax = delta+(2*dse))) +
   geom_hline(yintercept = 0, color = "light blue")
```
# combine all 10-5m temp diff
```{r}
diff.all <- rbind(bel.diff, dil.diff, cr.diff)
head(diff.all)
str(diff.all)
diff.all$Site <- as.factor(diff.all$Site)
```

```{r graph all diff temp from 3 sites}
pd <- position_dodge(0.5)

ggplot(diff.all, aes(as.numeric(m.y), (delta)), color = (Site)) + 
   geom_point(position = pd) +
   theme_classic() +
   labs(title = "Urban-E 10-5m Temperature", xlab = "Month/Year", ylab = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90)) +
    geom_errorbar(aes(ymin = delta-(2*dse), ymax = delta+(2*dse)),width = 0.1, position = pd) +
   geom_hline(yintercept = 0, color = "light blue")

ggplot(diff.all, aes(as.numeric(m.y), delta, color = Site)) + geom_point(position=pd) +
   theme_classic() +
   labs(title = "In Situ Temperature Difference between 10 and 5m", x = "Month/Year", y = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90)) +
   geom_smooth() +
   geom_hline(yintercept = 0, color = "dark blue") +
   scale_x_discrete(limits = levels(cr.diff$m.y))

ggplot(diff.all, aes(as.numeric(m.y), delta, color = Site)) + geom_point(position=pd) +
   theme_classic() +
      labs(title = "In Situ Temperature Difference between 10 and 5m", x="Month/Year", y = "deltaTemperature") +
   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    geom_errorbar(aes(ymin = delta-(2*dse), ymax = delta+(2*dse)),width = 0.1, position = pd) +
   geom_hline(yintercept = 0, color = "blue") +
      scale_x_discrete(limits = levels(cr.diff$m.y)) +
   geom_smooth() 
```


```{r dailymax ck data}
ck <- rbind(dil5, dil10, bel5, bel10, cr5, cr10)

#write.csv(ck, "ck_2015-2017_tempdat.csv")

ck.dmax <- ck %>% group_by(year, month, day, Site, Depth) %>%
   dplyr::summarize(dmax = max(Temp))
head(ck.dmax)

ck.dmaxse <- summarySE(ck.dmax, "dmax", c("month", "year", "Site", "Depth"), na.rm = T)
head(ck.dmaxse)

ck.dmaxse <- ck.dmaxse[-which(is.na(ck.dmaxse)),]

#remove partial months
ck.temp <- ck.dmaxse[-which((ck.dmaxse$N < 28)),]

colnames(ck.temp)[colnames(ck.temp) == "dmax"] <-"Temp"

head(ck.temp)
```
```{r all data inc partial months 2se}
ggplot(ck.dmaxse, aes(as.factor(month), dmax, color = Site)) + facet_grid(Depth~year) +
   geom_errorbar(aes(ymax=dmax+sd, ymin=dmax-sd), position=pd) +
   geom_point(position=pd) +
   theme_classic() +
   ggtitle("CK insitu temperature logger data - sd")

ggplot(ck.dmaxse, aes(as.factor(month), dmax, color = Site)) + facet_grid(Depth~year) +
   geom_errorbar(aes(ymax=dmax+(2*se), ymin=dmax-(2*se)), position=pd) +
   geom_point(position=pd) +
   theme_classic() +
   ggtitle("CK insitu temperature logger data all - 2 se")
```
```{r whole months 2se}
ggplot(ck.temp, aes(as.factor(month), Temp, color = Site)) + facet_grid(Depth~year) +
   geom_errorbar(aes(ymax=Temp+sd, ymin=Temp-sd), position=pd) +
   geom_point(position=pd) +
   theme_classic() +
   ggtitle("CK insitu temperature logger data - sd")

ggplot(ck.temp, aes(as.factor(month), Temp, color = Site)) + facet_grid(Depth~year) +
   geom_errorbar(aes(ymax=Temp+(2*se), ymin=Temp-(2*se)), position=pd) +
   geom_point(position=pd) +
   theme_classic() +
   ggtitle("CK insitu temperature logger data - 2 se")
```

```{r read in CRW data}
coralreefwatch <- read_csv(here::here("data/rawdata/temperature/CRWdat-timor_leste_end8AUG2017_R.csv"))

library(dplyr)
crw <- coralreefwatch %>% filter(YYYY > 2014) %>%
   filter(YYYY == 2015 & MM > 7 | YYYY > 2015)

crw.monthse <- summarySE(crw, "SST_MAX", c("YYYY", "MM"))
colnames(crw.monthse)[colnames(crw.monthse) == "SITE_D"] <- "GROUP"

crw.monthse$Site <- "CRWTL"

colnames(crw.monthse)[colnames(crw.monthse) == "MM"] <-"month"
colnames(crw.monthse)[colnames(crw.monthse) == "SST_MAX"] <-"Temp"
colnames(crw.monthse)[colnames(crw.monthse) == "YYYY"] <-"year"
head(crw.monthse)

crw.10se <- crw.monthse
crw.10se$Depth <- "10m"

crw.5se <- crw.monthse
crw.5se$Depth <- "5m"

head(crw.10se)
head(crw.5se)
```

```{r combine  sites 5 and 10 m depth montly mean from daily max, crw data}
temp <- rbind(ck.temp, crw.5se, crw.10se)
head(temp)
tail(temp)
str(temp)

temp$year <- as.factor(temp$year)
temp$month <- as.factor(temp$month)
temp$Site <- as.factor(temp$Site)
temp$Site <- relevel(temp$Site, ref = "CRWTL")
temp$Depth <- as.factor(temp$Depth)
temp$Depth <- relevel(temp$Depth, ref = "5m")

temp$m.y <- as.factor(paste(temp$month, temp$year, sep = "/"))
levels(temp$m.y)
temp$m.y = factor(temp$m.y,levels(temp$m.y)[c(21,24,3,5,7,1,9,11,13,15,17,19,22,25,4,6,8,2,10,12,14,16,18,20,23)])

#write_csv(temp, here::here("data/alltemp_TL.csv"))
```

```{r plot all sites}
pd <- position_dodge(0.9)

ggplot(temp, aes(m.y, Temp, color = Site)) + facet_grid(Depth~.) +
   geom_errorbar(aes(ymax=Temp+(2*se), ymin=Temp-(2*se)), position=pd) +
   geom_point(position=pd)+
      theme_classic() +
      ggtitle("Coral Reef Watch - In Situ Temperature Monthly Mean + 2SE") +
   xlab("Month/Year") + ylab("Temperature [C]") +
   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
      geom_hline(yintercept = 29.5, color = "light blue", linetype = 2) +
   geom_hline(yintercept = 30.5, color = "light blue") 
   
```

```{r filter overlapping Crw and c data}
library(tidyr)
temp.same <- temp %>% filter(m.y != "8/2015" & m.y != "9/2015" & m.y != "10/2015" & m.y != "11/2015" & 
                                m.y != "6/2017" & m.y != "7/2017" & m.y != "8/2017")
```


```{r histograph Temp, anova}
hist(temp.same$Temp)
head(temp.same)

temp.an <- aov((Temp) ~ Site* Depth + month, data = temp.same)
summary(temp.an)
plot(temp.an)
termplot(temp.an)
TukeyHSD(temp.an)

temp.an2 <- aov((Temp) ~ Site* Depth + year*month, data = temp.same)
summary(temp.an2)
plot(temp.an2)
termplot(temp.an2)
TukeyHSD(temp.an2)
```
```{r temp.same dates lm}
temp.lm <- lm(Temp ~ Site*Depth + month, data = temp.same)
summary(temp.lm)
plot(temp.lm)

anova(temp.lm)

plot(temp.lm$fitted.values, predict(temp.lm))
```