---
title: "Acropora counts, analysis by morphology"
author: "Caterine Kim"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in coral health survey data from 2015 and 2017 and combine into one data frame

```{r read in data, include=TRUE}
library(here) # to use relative file paths to read in data
library(readr)
comp1517 <- read_csv(here("data/CoralHealth-2015-2017-genmorph.csv")) 

library(dplyr)
comp1517_factor <- comp1517 %>%  mutate(across(where(is.character),as.factor))
   
comp1517_factor$Year <- as.factor(comp1517_factor$Year) # year also as a factor

head(comp1517_factor)
```

```{r create unique transect id}
comp1517_factor$long_id <-  as.factor(paste(comp1517_factor$Site2, comp1517_factor$Depth, comp1517_factor$Transect,
                                            sep = "_"))

levels(comp1517_factor$long_id)

ids <- read.csv(here::here("data/unique_ids.csv"))

comp1517_factor <- inner_join(comp1517_factor, ids,
                              by = 'long_id')
comp1517_factor$num_id <- as.factor(comp1517_factor$num_id)
```

## Tabulate acroporid count and analysis

```{r count acropora tabulate colonies, warning=FALSE}
library(tidyr)

ACRcount <- comp1517_factor %>% 
   group_by(Year, Site2, Depth, Transect, num_id, GEN, morph) %>% 
   dplyr::summarize(totmorph = sum(Number)) %>% 
        filter(GEN == "ACR") %>% 
      pivot_wider(names_from = morph,
                  values_from = totmorph,
                  values_fill = 0) %>%
   pivot_longer(bush:bottle, names_to = 'morph',
                values_to = 'totmorph')

ACRtab <- ACRcount %>% 
   filter(morph == 'corym' | morph == 'tab') %>%
   dplyr::summarize(tottab = sum(totmorph))

library(ggpubr) 
ggboxplot(
  ACRtab, x = "Site2", y = "tottab", facet.by = 'Depth',
  color = "Year", palette = "jco"
  )

# check nomality
hist(ACRtab$tottab)
hist(log10(ACRtab$tottab))
qqnorm(log10(ACRtab$tottab+.1))
library(car)
leveneTest(tottab ~ Year * Site2 * Depth, data = ACRtab)
```
```{r repeated measures anova tabulate}
# normal anova
summary(aov(log10(tottab + .1) ~ Year * Site2 * Depth +
               Error(num_id), data = ACRtab))

# mixed model approach
library(nlme)
acr.lme <- lme(log10(tottab + .1 ) ~ Year *Site2 * Depth, 
               random = ~1|num_id,
               data = ACRtab, na.action = na.exclude)
#acr.lme
summary(acr.lme)
library(car)
Anova(acr.lme) # used
library(emmeans)
emmeans(acr.lme, list(pairwise ~ Site2), adjust = "tukey")
```

```{r random intercept and slope}
acr.lme2 <- lme(log10(tottab + .1) ~ Year *Site2 * Depth, 
                random = ~Year|num_id,
               data = ACRtab, na.action = na.exclude)

summary(acr.lme2)
Anova(acr.lme2)
emmeans(acr.lme, list(pairwise ~ Site2), adjust = "tukey")

anova(acr.lme, acr.lme2)  # not significantly different
```

```{r average number of tabulate acroporids per site}
ACRtabave <- ACRtab %>% 
   group_by( Site2, GEN) %>% 
   dplyr::summarize(ave = mean(tottab), SE = sd(tottab)/n())
ACRtabave
```

# Branching acroporid count and analysis

```{r count acropora branching}
ACRbracount <- ACRcount %>% 
   filter(morph == "br" | morph == "bush" | morph == "stag") %>% 
   dplyr::summarize(totbra = sum(totmorph))

# boxplot
ggboxplot(
  ACRbracount, x = "Site2", y = "totbra", facet.by = 'Depth',
  color = "Year", palette = "jco"
  )

# check normality
hist(ACRbracount$totbra + 0.1)
hist(log10(ACRbracount$totbra +0.1))
qqnorm(log10(ACRbracount$totbra +0.1))
leveneTest(totbra ~ Year * Site2 * Depth, data = ACRbracount)
```
```{r repeated measures anova branching}
acrbra.lme <- lme(log10(totbra + 0.1) ~ Year * Site2 * Depth, 
                  random = ~1|num_id,
               data = ACRbracount, na.action = na.exclude)
acrbra.lme
summary(acrbra.lme) # lowest AIC
Anova(acrbra.lme)
emmeans(acr.lme, list(pairwise ~ Site2), adjust = "tukey")
emmeans(acr.lme, list(pairwise ~ Year), adjust = "tukey")
```

```{r branching random intercept and slope}
acrbra.lme2 <- lme(log10(totbra + 0.1) ~ Year * Site2 * Depth, random = ~Year|num_id,
               data = ACRbracount, na.action = na.exclude)
acrbra.lme2
summary(acrbra.lme2)
Anova(acrbra.lme2)

anova(acrbra.lme, acrbra.lme2) # models not significantly different 
```

```{r average branching acroporids}
# relevel factors 
ACRbracount$Depth <- relevel(ACRbracount$Depth, ref = "5m")

# average branching acroporid per site, depth, year
ACRbraave_site_d_yr <- ACRbracount %>% 
   group_by( Site2, Depth, Year, GEN) %>% 
   dplyr::summarize(ave = mean(totbra), SE = sd(totbra)/n()) 
ACRbraave_site_d_yr

ggplot(ACRbracount, 
       aes(x = Year, y = totbra, fill = Depth)) +
   geom_boxplot() +
   facet_wrap(vars(Site2)) +
   theme_classic() +
   theme(text = element_text(size = 16))

# save plot as pdf and jpg
ggsave(here::here("figures/ACRbra_counts_site_d_yr.pdf"), width = 7, height = 4)
ggsave(here::here("figures/ACRbra_counts_site_d_yr.jpg"), width = 7, height = 4)
```
