---
title: "Analysis of genera diversity"
author: "Catherine Kim"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Genera diversity analysis of coral belt transects 

Read in the data of coral genera counted on 15 x 2 belt transects. 

```{r read in 2015 and 2017 genera data, message=FALSE, warning=FALSE}
library(Rmisc)
library(here)
library(dplyr)
gen <- read.csv(here::here('data/genmorph.csv')) %>% 
   dplyr::mutate(across(where(is.character), as.factor))
   
gen$Year <- as.factor(gen$Year)  # year also as a factor
gen$Depth <- relevel(gen$Depth, ref = "5m")  # relevel so depth goes 5 then 10 m
```

```{r average number of corals per site and depth}
totcoral <- gen %>% 
   dplyr::select(ACA:PORmass) %>% 
   rowSums()

avecoral <- cbind(gen[,1:5], totcoral) %>% 
   group_by(Site, Depth, Year) %>% 
   dplyr::summarise(total = sum(totcoral))%>%
   group_by(Site, Depth) %>% 
   dplyr::summarise(ave = mean(total), SE = sd(total)/sqrt(n()))

# col per m/2
density <- avecoral$ave/60 
cbind(avecoral[,1:2], density)
   
```


```{r presence/absence total gen graph}
gen1 <- gen[which(colnames(gen) == 'ACA'):ncol(gen)]
head(gen1)
#add same morphs ACR, MONTI, POR
gen1$ACR <- gen1$ACR + gen1$ACRtab + gen1$ACRbr
gen1$ACRbr <- NULL
gen1$ACRtab <- NULL

gen1$POR <- gen1$PORmass + gen1$PORbr + gen1$PORother
gen1$PORmass <- NULL
gen1$PORbr <- NULL
gen1$PORother <- NULL

gen1$MONTI <- gen1$MONTI + gen1$MONTIbr
gen1$MONTIbr <- NULL

gen.pa <- gen1
gen.pa[gen.pa > 0] <- 1
gen.sum <- apply(gen.pa, 1, sum)
head(gen.sum)

gen.sum <- cbind(gen[1:5], gen.sum)
```

## Graph genera diversity

```{r summarySE pres/abs gen, warning=FALSE}
gen.sum.se <- summarySE(gen.sum, "gen.sum", c("Site", "Depth", "Year"))

library(ggplot2)
ggplot(gen.sum.se, aes(Year, gen.sum)) + geom_bar(stat = "identity") + 
   facet_grid(Depth~Site, switch = "x") +
 #  ggtitle("Present Genera - 2015, 2017") +
   geom_errorbar(aes(ymin = gen.sum-se, ymax=gen.sum+se), width = 0.2) +
   xlab("Site and Year") + ylab("Count of Genera") +
   theme_classic() +
      theme(axis.ticks.x = element_blank()) +
   theme(plot.title = element_text("sans", "bold",color = "black", 25)) +
   theme(text = element_text(size = 15)) 
   theme( strip.background= element_blank())
```

Genear meaned with SE across survey years.

```{r genera ave across yr}
gen.sum %>% 
   group_by(Site, Depth) %>% 
   summarize(meanG = mean(gen.sum),
             SE = sd(gen.sum)/sqrt(n()))
```

# Shannon's diversity on genera

```{r calculate shannon index, message=FALSE, warning=FALSE}
library(vegan)
shan <- diversity(gen1, "shannon")
shan <- round(shan,3)
gen.shan <- cbind(gen[1:5], shan)
head(gen.shan)

gen.shan.se <- summarySE(gen.shan, "shan", c("Site", "Depth", "Year"))
```

```{r shannon plot}
ggplot(gen.shan.se, aes(Year, shan)) + geom_bar(stat = "identity") + 
   facet_grid(Depth~Site, switch = "x") +
   geom_errorbar(aes(ymin = shan-se, ymax = shan+se), 
                 width = 0.2) +
   ylab("Shannon Index") +
   theme_classic() +
      theme(axis.ticks.x = element_blank()) +
   theme(plot.title = element_text("sans", "bold",color = "black", 25)) +
   theme(text = element_text(size = 15)) 
   theme( strip.background= element_blank())
ggsave(here::here("figures/FigA2_shannon_2015-2017.jpg"), height = 5, width = 7)
```

```{r shannon glm}
shan.glm <- lm(shan~Year*Site*Depth, data = gen.shan)
summary(shan.glm)
plot(shan.glm)
```
```{r check normality of shannon diversity, warning=FALSE}
hist(gen.shan$shan)
hist(sqrt(gen.shan$shan))

library(car)
leveneTest(shan~Year*Site*Depth, data = gen.shan) # not significant
leveneTest(sqrt(shan)~Year*Site*Depth, data = gen.shan) # not significant
```

```{r anova Shannon, warning=FALSE}
library(nlme)
shan.lme2 <- lme(sqrt(shan) ~ Year * Site*Depth, random = ~1|num_id, data = gen.sum, na.action = na.exclude)
plot(shan.lme2)
summary(shan.lme2)
Anova(shan.lme2)

library(emmeans)
emmeans(shan.lme2, list(pairwise ~ Site:Depth), adjust = "tukey")
```
