---
title: "Repeated measures anova of hard coral from benthic composition"
author: "Catherine Kim"
date: "March 4th 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Statistics on benthic composition from 15m Line Intercept Transects (LIT) in Timor-Leste from 2015 and 2017

```{r Read in data from 15 m line intercept transects, warning=FALSE}
library(here)
bencomp <- read.csv(here::here('data/bencomp-transect-20152017.csv'))

# change variables to factors
bencomp$Year <- as.factor(bencomp$Year)
bencomp$Site2 <- as.factor(bencomp$Site2)
bencomp$Depth <- as.factor(bencomp$Depth)
head(bencomp)
```

```{r check normality}
hist(bencomp$HardCoral)
qqnorm(bencomp$HardCoral)
qqline(bencomp$HardCoral)
library(car)
leveneTest(HardCoral ~ Year * Site2 * Depth, 
           data = bencomp)

hist(sqrt(bencomp$HardCoral))
qqnorm(sqrt(bencomp$HardCoral))
qqline(sqrt(bencomp$HardCoral))
leveneTest(sqrt(HardCoral) ~ Year * Site2 * Depth, 
           data = bencomp)
```

```{r repeated measures anova on hard coral cover}
library(nlme)
cor.lme <- lme(sqrt(HardCoral) ~ Site2 * Depth * Year, 
               random = ~1|num_id, 
               data = bencomp, na.action = na.exclude)
cor.lme
summary(cor.lme)
plot(cor.lme)
Anova(cor.lme) # car package

library(emmeans)
tuk.cor <- emmeans(cor.lme, list(pairwise ~ Site2:Depth:Year), adjust = "tukey")

pair.cor <- as.data.frame(tuk.cor$`pairwise differences of Site2, Depth, Year`)

sig.pair.cor <- pair.cor[which(pair.cor$p.value < 0.05),]
sig.pair.cor
```

```{r average coral cover}
## summarized by coral site depth year
library(tidyr)
library(dplyr)
coral.ave <- bencomp %>% 
   group_by(Site2, Depth, Year) %>% 
   dplyr::summarize(corave = mean(HardCoral),
                    corSE = sd(HardCoral)/sqrt(n()))
#    
# library(ggpubr) 
# ggboxplot(
#   ACRtab, x = "Site", y = "tottab", facet.by = 'Depth',
#   color = "Year", palette = "jco"
#   )

# site and depth average across years
bencomp %>% 
   group_by(Site2, Depth) %>% 
   dplyr::summarize(corave = mean(HardCoral),
                    corSE = sd(HardCoral)/sqrt(n()))
```

## Stacked bargraph of LIT benthic composition

```{r pivot long for graph}
library(dplyr)
bencomp_long <- bencomp %>% 
   pivot_longer(CCA:Turf, names_to = 'Major.Category', values_to = 'Percent') %>% 
   group_by(Year, Site2, Depth, Major.Category) %>% 
   dplyr::summarize(ave = mean(Percent))
```

```{r stacked bar graph of 2015 and 2017}
bencomp_long$Major.Category <- as.factor(bencomp_long$Major.Category)
levels(bencomp_long$Major.Category)

bencomp_long$Major.Category <- relevel(bencomp_long$Major.Category, ref = "HardCoral")

bencomp$Depth <- relevel(bencomp$Depth, ref = "5m")
head(bencomp_long)

library(ggplot2)
library(colorspace)
ggplot(bencomp_long, 
       aes(x=Year,y = ave, fill= factor(Major.Category,
                                        levels = c("Turf","Substrate.Sand", "SoftCoral","Macroalgae", "Invert", "CCA", "HardCoral")))) + 
   geom_bar( position="stack", stat="identity") +   facet_grid(Depth~Site2,switch = "x") +
   labs(x = "Site and Year", y = "Percent") +
   theme_classic() +
   #theme(plot.title = element_text("sans", "bold",color = "black", 25)) +
   theme(panel.border = element_blank(), 
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         panel.background = element_blank(),
         text = element_text(size = 12)) +
   scale_fill_discrete_divergingx("Spectral", 
                                  name = "Benthic Category",
                                  labels = c("Turf Algae","Substrate/Sand", "Soft Coral","Macroalgae", "Invertebrates", "CCA", "Hard Coral"))

ggsave(here::here('figures/Fig3_TL2015-2017_bencomp_bargraph.jpg'),
       height = 4, width = 7, dpi = 300)

```
