---
title: "count-dis-ACRtab"
author: "CKim"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read in data, include=FALSE}
library(here)
library(readr)
comp1517 <- read_csv(here::here("data/CoralHealth-2015-2017edit042021-R-genmorph.csv")) 

library(dplyr)
comp1517_factor <- comp1517 %>%  mutate(across(where(is.character),as.factor))
   
comp1517_factor$Year <- as.factor(comp1517_factor$Year) # year also as a factor

head(comp1517_factor)
```
```{r creatae unique transect id}
comp1517_factor$long_id <- as.factor(paste(comp1517_factor$Site,
                                           comp1517_factor$Depth,
                                           comp1517_factor$Transect,
                                           sep = "_"))

levels(comp1517_factor$long_id)
#write.csv(levels(comp1517_factor$id), "unique_ids.csv")
# write levels and add num id
# read file with num id
ids <- read.csv(here::here("data/unique_ids_wnum.csv"))

library(dplyr)
comp1517_factor <- inner_join(comp1517_factor, ids, by = 'long_id')
comp1517_factor$num_id <- as.factor(comp1517_factor$num_id)
```

## Health Category summaries
```{r}
distot <- comp1517_factor %>% 
   group_by(Year, H1) %>% 
   summarize(total = sum(Number))


distotgen <- comp1517_factor %>% 
   group_by(Year,GEN, morph,H1) %>% 
   summarize(total = sum(Number))

WStotgen <- comp1517_factor %>% 
   group_by(Year,GEN, morph,H1) %>% 
   summarize(total = sum(Number)) %>% 
   filter(H1 == "WS")

GAtotgen <- comp1517_factor %>% 
   group_by(Year,GEN, morph,H1) %>% 
   summarize(total = sum(Number)) %>% 
  filter(H1 == "GA")
```


```{r count acropora tabs}
library(tidyr)
library(dplyr)

ACRcount <- comp1517_factor %>% 
   group_by(Year, Site, Depth, Transect, num_id, GEN, morph) %>% 
   summarize(tot = sum(Number))%>% 
 
      group_by(Year, Site, Depth, Transect,num_id, GEN, morph) %>% 
   summarize(totmorph = sum(tot))%>% 
      filter(GEN == "ACR") %>% 
      pivot_wider(names_from = morph, 
                  values_from = totmorph,
                  values_fill = 0) %>% 
   pivot_longer(bush:bottle, names_to = 'morph', values_to = 'totmorph')

ACRtab <- ACRcount %>% filter(morph == 'corym' | morph == 'tab') %>%
   summarize(tottab = sum(totmorph))


library(ggpubr) 
ggboxplot(
  ACRtab, x = "Site", y = "tottab", facet.by = 'Depth',
  color = "Year", palette = "jco"
  )

hist(ACRtab$tottab)
hist(log10(ACRtab$tottab))
qqnorm(log10(ACRtab$tottab+.1))

acrtab.an <- aov(log10(tottab+.1) ~ Site * Depth * Year, data = ACRtab)
summary(acrtab.an)
plot(acrtab.an)
```
```{r repeated measures anova tabulate}
# normall anova
summary(aov(log10(totmorph) ~ Year + Site + Depth + Error(num_id), data = ACRcount))

# mixed model approach
library(nlme)
acr.lme <- lme(log10(totmorph) ~ Year +Site + Depth, random = ~1|num_id,
               data = ACRcount, na.action = na.exclude)
acr.lme
summary(acr.lme)
library(car)
Anova(acr.lme)
library(emmeans)
emmeans(acr.lme, list(pairwise ~ Site), adjust = "tukey")

#install.packages("devtools")
devtools::install_github("easystats/easystats")
library(easystats)

#library(psycho)
#results <- psycho::analyze(acr.lme)

# random intercept and slope
acr.lme2 <- lme(log10(totmorph) ~ Year +Site + Depth, random = ~Year|num_id,
               data = ACRcount, na.action = na.exclude)
acr.lme2
summary(acr.lme2)
Anova(acr.lme)
emmeans(acr.lme, list(pairwise ~ Site), adjust = "tukey")

ACRtabave <- ACRcount %>% 
   group_by( Site, GEN) %>% 
   summarize(ave = mean(totmorph), SE = sd(totmorph)/n()) 
```
# Anova for branching acroporids
```{r count acropora branching}
ACRbracount <- comp1517_factor %>% 
   group_by(Year, Site, Depth, Transect, num_id, GEN, morph) %>% 
   summarize(tot = sum(Number)) %>% 
   filter(morph == "br" | morph == "bush" | morph == "stag") %>% 
      group_by(Year, Site, Depth, Transect, num_id, GEN) %>% 
   summarize(totmorph = sum(tot)) %>% 
      filter(GEN == "ACR")

ggboxplot(
  ACRbracount, x = "Site", y = "totmorph", facet.by = 'Depth',
  color = "Year", palette = "jco"
  )

hist(ACRbracount$totmorph)
hist(log10(ACRbracount$totmorph))
qqnorm(log10(ACRcount$totmorph))

ACRbraave <- ACRbracount %>% 
   group_by( Site, GEN) %>% 
   summarize(ave = mean(totmorph), SE = sd(totmorph)/n()) 
ACRbraave
```
```{r repeated measures anova branching}

acrbra.lme <- lme(log10(totmorph) ~ Year +Site + Depth, random = ~1|num_id,
               data = ACRbracount, na.action = na.exclude)
acrbra.lme
summary(acrbra.lme) # lowest AIC
Anova(acrbra.lme)
emmeans(acr.lme, list(pairwise ~ Site), adjust = "tukey")

# random intercept and slope
acrbra.lme2 <- lme(log10(totmorph) ~ Year +Site + Depth, random = ~Year|num_id,
               data = ACRbracount, na.action = na.exclude)
acrbra.lme2
summary(acrbra.lme2)
Anova(acrbra.lme)
emmeans(acrbra.lme, list(pairwise ~ Site), adjust = "tukey")

```

```{r repeated measured ACR tab count with rstatix package}
ACRcount$T.orig <- 1:24

ACRcount %>%
  group_by(Site, Depth, Year) %>%
  get_summary_stats(totmorph, type = "mean_sd")

library(ggpubr)
ggboxplot(
  ACRcount, x = "Site", y = "totmorph", facet.by = 'Depth',
  color = "Year", palette = "jco"
  )

library(rstatix)
tab.aov <- anova_test(data = ACRcount, dv = totmorph, wid = num_id, 
                      within = c(Site, Depth, Year))
colnames(ACRcount)


anova_test(data = ACRcount, totmorph ~ Year +Site + Depth +
              Error(num_id/(Year + Site + Depth)))
```


