---
title: "Repeated measures anova of hard coral from benthic composition"
author: "CKim"
date: "12/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Rmisc)
library(tidyr)
library(dplyr)
library(ggplot2)
library(here)
```

## Statistics on benthic composition from 15m Line Intercept Transects (LIT) in Timor-Leste from 2015 and 2017

```{r Read in data from 15 m line intercept transects}
bencomp <- read.csv(here::here('data/bencomp-transect-20152017.csv'))

# change variables to factors
bencomp$Year <- as.factor(bencomp$Year)
bencomp$Site2 <- as.factor(bencomp$Site2)
bencomp$Depth <- as.factor(bencomp$Depth)
head(bencomp)
```

```{r check normality}
hist(bencomp$HardCoral)
qqnorm(bencomp$HardCoral)
qqline(bencomp$HardCoral)
library(car)
leveneTest(HardCoral ~ Year * Site2 * Depth, data = bencomp)

hist(sqrt(bencomp$HardCoral))
qqnorm(sqrt(bencomp$HardCoral))
qqline(sqrt(bencomp$HardCoral))
leveneTest(sqrt(HardCoral) ~ Year * Site2 * Depth, data = bencomp)
```

```{r repeated measures anova on hard coral cover}
library(nlme)
cor.lme <- lme(sqrt(HardCoral) ~ Site2 * Depth * Year, random = ~1|num_id, data = bencomp, na.action = na.exclude)
cor.lme
summary(cor.lme)
plot(cor.lme)
Anova(cor.lme) # car package

library(emmeans)
tuk.cor <- emmeans(cor.lme, list(pairwise ~ Site2:Depth:Year), adjust = "tukey")
pair.cor <- as.data.frame(tuk.cor$`pairwise differences of Site2, Depth, Year`)
sig.pair.cor <- pair.cor[which(pair.cor$p.value < 0.05),]
sig.pair.cor
```

```{r average coral cover}
## summarized by coral site depth year
coral.ave <- bencomp
   group_by(Site2, Depth, Year) %>% 
   dplyr::summarize(corave = mean(HardCoral),
                    corSE = sd(HardCoral)/sqrt(n()))
   
library(ggpubr) 
ggboxplot(
  ACRtab, x = "Site", y = "tottab", facet.by = 'Depth',
  color = "Year", palette = "jco"
  )
```

