---
title: "genera diversity"
author: "Catherine Kim"
date: "April 23, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Genera diversity analysis of coral belt transects 

```{r read in 2015 and 2017 genera data}
library(Rmisc)
library(here)
library(dplyr)
gen <- read.csv(here::here('data/genmorph.csv')) %>% 
   dplyr::mutate(across(where(is.character), as.factor))
   
gen$Year <- as.factor(gen$Year)  # year also as a factor
gen$Depth <- relevel(gen$Depth, ref = "5m")  # relevel so depth goes 5 then 10 m
```

```{r presence/absence total gen graph}
gen1 <- gen[which(colnames(gen) == 'ACA'):ncol(gen)]
head(gen1)
#add same morphs ACR, MONTI, POR
gen1$ACR <- gen1$ACR + gen1$ACRtab + gen1$ACRbr
gen1$ACRbr <- NULL
gen1$ACRtab <- NULL

gen1$POR <- gen1$PORmass + gen1$PORbr + gen1$PORother
gen1$PORmass <- NULL
gen1$PORbr <- NULL
gen1$PORother <- NULL

gen1$MONTI <- gen1$MONTI + gen1$MONTIbr
gen1$MONTIbr <- NULL

gen.pa <- gen1
gen.pa[gen.pa > 0] <- 1
gen.sum <- apply(gen.pa, 1, sum)
head(gen.sum)

gen.sum <- cbind(gen[1:5], gen.sum)
```

## Graph genera diversity

```{r summarySE pres/abs gen, graph}
gen.sum.se <- summarySE(gen.sum, "gen.sum", c("Year", "Site", "Depth"))

library(ggplot2)
ggplot(gen.sum.se, aes(Year, gen.sum)) + geom_bar(stat = "identity") + facet_grid(Depth~Site, switch = "x") +
 #  ggtitle("Present Genera - 2015, 2017") +
   geom_errorbar(aes(ymin = gen.sum-se, ymax=gen.sum+se), width = 0.2) +
   xlab("Site and Year") + ylab("Count of Genera") +
   theme_classic() +
      theme(axis.ticks.x = element_blank()) +
   theme(plot.title = element_text("sans", "bold",color = "black", 25)) +
   theme(text = element_text(size = 15)) 
   theme( strip.background= element_blank())
#ggsave("figures/genera_2015-2017.pdf", height = 5, width = 7)
```

# Shannon's diversity on genera
```{r calculate shannon index}
library(vegan)
shan <- diversity(gen1, "shannon")
shan <- round(shan,3)
gen.shan <- cbind(gen[1:5], shan)
head(gen.shan)
```

```{r graph shannon year, site, depth}
shan.se <- summarySE(gen.shan, "shan", c("Year", "Site", "Depth"))
shan.se

ggplot(shan.se, aes(Site, shan)) + geom_bar(stat = "identity") + facet_grid(Depth~Year) +
   ggtitle("Shannon's Diversity Index, 2015 and 2017") +
   geom_errorbar(aes(ymin = shan-se, ymax=shan+se), width = 0.2)

# facet by site, year side by side
ggplot(shan.se, aes(Year, shan)) + geom_bar(stat = "identity") + facet_grid(Depth~Site, switch = "x") +
   ggtitle("Coral Genera Diversity - 2015, 2017") +
   geom_errorbar(aes(ymin = shan-se, ymax=shan+se), width = 0.2) +
   theme_classic() +
   theme(axis.ticks.x = element_blank()) +
   labs(x = "", y = "Shannon Index") +
   theme(plot.title = element_text("sans", "bold",color = "black", 25)) +
   theme(text = element_text(size = 15)) 
   theme( strip.background= element_blank())

```

```{r shannon glm}
shan.glm <- lm(shan~Year*Site*Depth, data = gen.shan)
summary(shan.glm)
plot(shan.glm)
```
```{r check normality of shannon diversity}
hist(gen.shan$shan)
hist(sqrt(gen.shan$shan))

library(car)
leveneTest(shan~Year*Site*Depth, data = gen.shan) # not significant
leveneTest(sqrt(shan)~Year*Site*Depth, data = gen.shan) # not significant
```

```{r anova Shannon}
library(nlme)
shan.lme2 <- lme(sqrt(shan) ~ Year * Site*Depth, random = ~1|num_id, data = gen.sum, na.action = na.exclude)
plot(shan.lme2)
summary(shan.lme2)
Anova(shan.lme2)
library(emmeans)
emmeans(shan.lme2, list(pairwise ~ Site:Depth), adjust = "tukey")
```
