---
title: "Disease and compromised heatlh 2015-2017"
author: "Catherine Kim"
date: "April 23, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read in  Site to Site2 urban/rural names}
library(tidyr)
library(dplyr)
library(ggplot2)

site2 <- read.csv(here::here("data/Site-Site2.csv"))
colnames(site2)[1] <- "Site"
head(site2)
```
```{r read in data}
library(here)
compdat <- read.csv(here::here('data/comp7_tave.csv')) %>% 
   pivot_longer(AllAlgae:WS, names_to = 'Status', values_to = 'Percent') %>% 
   full_join(site2, by = "Site") %>% 
   mutate_if(is.character, as.factor) 

compdat$Year <- as.factor(compdat$Year)
head(compdat)
compdat <- compdat[-which(is.na(compdat)),]
```

```{r ave compromised total}
compdat %>% 
   group_by(Year, Site2, Depth, Transect) %>% 
   filter(Status != 'Healthy')%>% 
   dplyr::summarize(comp_transt = sum(Percent))%>% 
   ungroup() %>% 
   dplyr::summarize(avecomp = mean(comp_transt), SE = sd(comp_transt)/sqrt(n()))
```

# average comprimese states by site, depth, year
```{r average group by year, site, depth}
compall <- compdat %>% 
   group_by(Year, Site2, Depth, Status) %>% 
   dplyr::summarize(avePer = mean(Percent),
                                  SE = sd(Percent)/sqrt(n()))
compall
```
# stacked graph without depth facet

```{r groupby year and site}
compall_nodepth <- compdat %>% 
   group_by(Year, Site2, Status) %>% 
   dplyr::summarize(avePer = mean(Percent))

compall_nodepth$Status <- factor(compall_nodepth$Status, levels=c("WS", "OTH", "TL", "CCA","AllAlgae", "BL", "Healthy"))
```

```{r no facet by depth}
ggplot(compall_nodepth, aes((Year), avePer,  fill = Status)) +
   facet_grid(.~Site2, switch = "x") +
    geom_bar(position="stack", stat="identity")+ #, color = "black") +
   ggtitle("Signs of Compromised Health 2015, 2017") +
   theme_classic() +
labs(x = "", y = "Percent") +
   theme(plot.title = element_text("sans", "bold",color = "black", 15)) +
   theme(text = element_text(size = 16)) +
   theme(axis.ticks.x = element_blank()) + #, panel.background = element_rect("gray85"))+
   theme(axis.text.x = element_text(hjust = 0.5),
         legend.title = element_blank())+
   scale_fill_brewer(palette="RdYlBu")
ggsave(here::here('figures/stacked-comphealth-20152017-nodepth.jpg'), width = 7, height = 4)
```


