---
title: "Stable isotope analysis"
author: "Catherine Kim"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Macroalgae collected on transects in Timor-Leste 2015 stable isotope analysis

```{r read in data, warning=FALSE}
library(here)
library(tidyverse)

here()
dat <- read.csv(here("data/StableIso_cleaned.csv"), header = TRUE) %>%   #no bad runs, missing site info
   mutate_if(is.character, as.factor)

StableIso_cleaned <- read_csv(here("data/StableIso_cleaned.csv"))
head(dat)
nrow(dat)
is.na(dat$d15N)
dat$Depth <- relevel(dat$Depth, ref = "5m")
```

```{r}
# calculate C:N
dat$CN <- dat$P.C/dat$P.N

# Wilcox test, means of 2 algae different? 
wilcox.test(d15N ~ Algae, data = dat)
# p = 0.025 

SE=function(x)
{
   sqrt(var(x)/length(x))
}

hrs <- function(u) {
   x <- u * 3600
   return(x)
}
```

### Find outliers

Knitting does not work because this chunk requires yes/no response in the console.

```{r outlier function}
## Tukey's outlier code 
source("http://goo.gl/UUyEzD")
# outlierKD(dat, variable)

outlierKD <- function(dt, var) {
   var_name <- eval(substitute(var),eval(dt))
   na1 <- sum(is.na(var_name))
   m1 <- mean(var_name, na.rm = T)
   par(mfrow=c(2, 2), oma=c(0,0,3,0))
   boxplot(var_name, main="With outliers")
   hist(var_name, main="With outliers", xlab=NA, ylab=NA)
   outlier <- boxplot.stats(var_name)$out
   mo <- mean(outlier)
   var_name <- ifelse(var_name %in% outlier, NA, var_name)
   boxplot(var_name, main="Without outliers")
   hist(var_name, main="Without outliers", xlab=NA, ylab=NA)
   title("Outlier Check", outer=TRUE)
   na2 <- sum(is.na(var_name))
   cat("Outliers identified:", na2 - na1, "n")
   cat("Propotion (%) of outliers:", round((na2 - na1) / sum(!is.na(var_name))*100, 1), "n")
   cat("Mean of the outliers:", round(mo, 2), "n")
   m2 <- mean(var_name, na.rm = T)
   cat("Mean without removing outliers:", round(m1, 2), "n")
   cat("Mean if we remove outliers:", round(m2, 2), "n")
   response <- readline(prompt="Do you want to remove outliers and to replace with NA? [yes/no]: ")
   if(response == "y" | response == "yes"){
      dt[as.character(substitute(var))] <- invisible(var_name)
      assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
      cat("Outliers successfully removed", "n")
      return(invisible(dt))
   } else{
      cat("Nothing changed", "n")
      return(invisible(var_name))
   }
}
```

```{r data without outliers}
library(outliers)
   outlier(dat$d15N)

dat.out <- as.data.frame(outlierKD(dat, d15N))
nrow(dat)
dat.out$CN <- dat.out$P.C/dat.out$P.N
dat.out[which(is.na(dat.out$d15N)),]
dat.nona <- (na.omit(dat.out))

dat.noout.ave <- dat.nona %>% 
   group_by(Site2, Algae) %>% 
   dplyr::summarize(avedN = mean(d15N),
             SEdN = sd(d15N)/n(),
             avepN = mean(P.N),
             SEpN = sd(P.N)/n(),
             aveCN = mean(CN),
             SECN = sd(CN)/n())
dat.noout.ave[order(dat.noout.ave$Algae, decreasing = T),]
```

## subset Chlorodesmis

```{r}
chl <- subset(dat, dat$Algae == "Chlorodesmis") %>% 
   droplevels()
head(chl)
nrow(chl)

library(plyr)
chl.site <- ddply(chl, c("Site2"), summarize, ave = mean(d15N))
head(chl.site)
chl.sd <- ddply(chl, c("Site"), summarize, sdev = sd(d15N))
head(chl.sd)
chl.se <- ddply(chl, c("Site2"), summarize, se = SE(d15N))
head(chl.se)
chl.site$se <- chl.se$se

chl.sidpt <- ddply(chl, c("Site2", "Depth", "Transect"), summarize, ave = mean(d15N))
head(chl.sidpt)
chl.sidpt.se <- ddply(chl, c("Site2", "Depth", "Transect"), summarize, se = SE(d15N))
head(chl.sidpt.se)
chl.sidpt$se <- chl.sidpt.se$se
```

## Subset Halimeda

```{r}
hal <- subset(dat.nona, dat$Algae == "Halimeda")
hal <- na.omit(hal)
head(hal)
nrow(hal)
hal.site <- ddply(hal, c("Site2"), summarize, ave = mean(d15N))
hal.site.se <- ddply(hal, c("Site2"), summarize, se = SE(d15N))
hal.site$se <- hal.site.se$se
head(hal.site)

hal.sidp <- ddply(hal, c("Site", "Depth"), summarize, ave = mean(d15N))
(hal.sidp)
hal.t <- ddply(hal, c("Site2", "Depth", "Transect"), summarize, ave = mean(d15N))
hal.t
hal.t.se <- ddply(hal, c("Site2", "Depth", "Transect"), summarize, se = SE(d15N))
hal.t$se <- hal.t.se$se
```

# Analysis

## Halimeda Analysis

```{r Halimeda analysis of d15N }
library(agricolae)
h.dn.mod <- lm(d15N ~ Site2*Depth, data = hal, contrasts= list(Site2='contr.sum', Depth = 'contr.sum'))
summary(h.dn.mod)
plot(h.dn.mod)
h.A <- Anova(h.dn.mod, type = "3")
h.A
```

```{r hal d15N posthoc tests}
library(multcomp)
hdn.mc = glht(h.dn.mod,
          mcp(Site2 = "Tukey"))

summary(hdn.mc, test=adjusted("single-step"))
multcomp::cld(hdn.mc)

library(emmeans)
pairs(emmeans(h.dn.mod, 'Site2'))
hdn.marginal = emmeans(h.dn.mod,
                   ~ Site2)

pairs(hdn.marginal, adjust="tukey")

library(multcompView)
cld(hdn.marginal, adjust="tukey", Letters=letters)
```
```{r mean hal d15N by site}
hal %>% #
   group_by(Site2) %>% 
   dplyr::summarize(halave = mean(d15N), SE = sd(d15N)/sqrt(n()))
```

```{r Halimeda percent N}
# PN
h.pn.mod <- lm(log10(P.N) ~ Site2*Depth, data = hal, contrasts= list(Site2='contr.sum', Depth = 'contr.sum'))
plot(h.pn.mod)

hpn.A <- Anova(h.pn.mod, type = "3")
hpn.A

pairs(emmeans(h.pn.mod, 'Site2'))
hpn.marginal = emmeans(h.pn.mod,
                   ~ Site2)

pairs(hpn.marginal, adjust="tukey")

cld(hpn.marginal, adjust="tukey", Letters=letters)
```

```{r mean hal %N by site}
hal %>% #
   group_by(Site2) %>% 
   dplyr::summarize(halave = mean(P.N), SE = sd(P.N)/sqrt(n()))
```

```{r Halimeda C to N ratio}
# CN
h.cn.mod <- lm(CN ~ Site2*Depth, data = hal, contrasts= list(Site2='contr.sum', Depth = 'contr.sum'))
plot(h.cn.mod)
hcn.A <- Anova(h.cn.mod, type = "3")
hcn.A

pairs(emmeans(h.cn.mod, 'Site2'))
hcn.marginal = emmeans(h.pn.mod,
                   ~ Site2)

pairs(hcn.marginal, adjust="tukey")

cld(hcn.marginal, adjust="tukey", Letters=letters)
```

```{r mean hal CN by site}
hal %>% #
   group_by(Site2) %>% 
   dplyr::summarize(halave = mean(CN), SE = sd(CN)/sqrt(n()))
```

## Chlorodesmis without 3 samples from rural-E, give NAs for depth if included

```{r chlorodesmis}
# dN
c.dn.mod <- lm(d15N ~ Site2*Depth, data = chl[-c(20:22),], contrasts= list(Site2='contr.sum', Depth = 'contr.sum', na.omit))
summary(c.dn.mod)
plot(c.dn.mod)
c.A <- Anova(c.dn.mod, type = "3", singular.ok = T)
c.A

pairs(emmeans(c.dn.mod, 'Site2'))
cdn.marginal = emmeans(c.dn.mod,
                   ~ Site2)

pairs(cdn.marginal, adjust="tukey")

cld(cdn.marginal, adjust="tukey", Letters=letters)
```

```{r mean chl d15N by site}
chl %>% #
   group_by(Site2) %>% 
   dplyr::summarize(chlave = mean(d15N), SE = sd(d15N)/sqrt(n()))
```

```{r chlorodesmis percent nitrogen}
# PN
c.pn.mod <- lm(P.N ~ Site2*Depth, data = chl[-c(20:22),], contrasts= list(Site2='contr.sum', Depth = 'contr.sum'))
summary(c.pn.mod)
plot(c.pn.mod)

cpn.A <- Anova(c.pn.mod, type = "3", singular.ok = T)
cpn.A

cpn.marginal = emmeans(c.pn.mod, ~ Site2)
pairs(cpn.marginal, adjust="tukey")
cld(cpn.marginal, adjust="tukey", Letters=letters)

chl %>% 
   group_by(Site2) %>% 
   dplyr::summarize(chlave = mean(P.N), SE = sd(P.N)/sqrt(n()))
```

```{r chlorodesmis C to N ratio}
c.cn.mod <- lm(CN ~ Site2*Depth, data = chl[-c(20:22),], contrasts= list(Site2='contr.sum', Depth = 'contr.sum'))
plot(c.cn.mod)
ccn.A <- Anova(c.cn.mod, type = "3")
ccn.A

ccn.marginal = emmeans(c.cn.mod, ~ Depth)
pairs(ccn.marginal, adjust="tukey")
cld(ccn.marginal, adjust="tukey", Letters=letters)

chl %>% 
   group_by(Site2) %>% 
   dplyr::summarize(chlave = mean(CN), SE = sd(CN)/sqrt(n()))
```
